spring.application.name=bodubodu

# SERVER
server.port=8080

# SUPABASE DATABASE
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?
spring.datasource.username=postgres.fqerpqnjopmyryanaeda
spring.datasource.password=A2UrF%fP5f#!jX-
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect